version: "3.8"
services:
  nginx:
    hostname: procstop-nginx
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "8080:80"
  php:
    hostname: procstop-php
    build:
      context: .
      dockerfile: Dockerfile.php
